### ISSUE TITLE
dalle mini command not working

### ISSUE THREAD

**Issue by duvbolone** [anniwth/Quasar#1]
The /dalle-mini command isn't working.
But it seems it's not an issue on your side, not sure tho

https://github.com/borisdayma/dalle-mini/issues/211

**Comment by adrak0** [comment]
This is an issue with the backend server cause of clogged traffic on the server.
Will be fixed soon.

**Comment by duvbolone** [comment]
Ok
Maybe add it to the description of the command tho, for now at least
